package com.ainosoft.server.binding;

import java.io.Serializable;
import java.util.HashMap;

import org.appops.altshared.shared.altcore.StaticsRegistry;

/**
 * @author vedang@ainosoft.com
 * @CreatedOn 09-Oct-2015
 * @Responsibility
 */
public class AddressBookStaticRegistryStore implements StaticsRegistry {

	HashMap<String, Serializable>	staticReferencesMap	= new HashMap<String, Serializable>();

	/**
	 * 
	 */
	public AddressBookStaticRegistryStore() {
		registerAllStaticReferences();
	}

	@Override
	public Serializable getStaticReference(String name) {
		return staticReferencesMap.get(name);
	}

	/* (non-Javadoc)
	 * @see org.appops.shared.altcore.StaticsRegistry#isReferenceNamePresent(java.lang.String)
	 */
	@Override
	public boolean isReferenceNamePresent(String name) {
		return staticReferencesMap.containsKey(name);
	}

	/* (non-Javadoc)
	 * @see org.appops.shared.altcore.StaticsRegistry#isReferencePresent(java.io.Serializable)
	 */
	@Override
	public String isReferencePresent(Serializable reference) {
		for (String name : staticReferencesMap.keySet()) {
			if (staticReferencesMap.get(name).equals(reference)) {
				return name;
			}
		}
		return null;
	}

	/* (non-Javadoc)
	 * @see org.appops.shared.altcore.StaticsRegistry#registerAllStaticReferences()
	 */
	@Override
	public void registerAllStaticReferences() {

		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.ButtonFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.CheckBoxFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.NAME",
				org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.VALUE",
				org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.NAME",
				org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.VALUE",
				org.appops.ui.gwt.fieldex.DateFieldEx.HasProperties.VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.ICON",
				org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.ICON);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.ICON",
				org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasProperties.ICON);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.IconLabelFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.IMAGE_URL",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.IMAGE_URL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.IMAGE_URL",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.IMAGE_URL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.ImageFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.MAX_LENGTH",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.MAX_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.VISIBLE_LENGTH",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.VISIBLE_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTED_TEXT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTED_TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_START",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_START);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_END",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_END);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECT_ALL",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECT_ALL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.MAX_LENGTH",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.MAX_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.VISIBLE_LENGTH",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.VISIBLE_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTED_TEXT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTED_TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_START",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_START);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_END",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECTION_END);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECT_ALL",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.SELECT_ALL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.LabelFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LayoutSnippetEx.HasProperties.MODEL",
				org.appops.ui.gwt.fieldex.LayoutSnippetEx.HasProperties.MODEL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LayoutSnippetEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.LayoutSnippetEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.HREF",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.HREF);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.HREF",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.HREF);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.LinkFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.NAME",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasMethods.setItemText",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasMethods.setItemText);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.NAME",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ListFieldEx.HasMethods.setItemText",
				org.appops.ui.gwt.fieldex.ListFieldEx.HasMethods.setItemText);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.ParagraphFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.RadioButtonFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MIN",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MIN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MAX",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MAX);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_STEP",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_STEP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_VALUE",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.VALUE_CHANGE_EVENT",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.VALUE_CHANGE_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MIN",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MIN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MAX",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_MAX);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_STEP",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_STEP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_VALUE",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.R_VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.VALUE_CHANGE_EVENT",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.VALUE_CHANGE_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.SliderFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.SubmitFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.FIELDNAME",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.FIELDNAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTED_TEXT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTED_TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_START",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_START);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_END",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_END);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECT_ALL",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECT_ALL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.VALUE",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasMethods.setSelectionPosition",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasMethods.setSelectionPosition);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.INPUT_EVENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.INPUT_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.VALUE_CHANGE_EVENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.VALUE_CHANGE_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTED_TEXT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTED_TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_START",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_START);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_END",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECTION_END);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECT_ALL",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.SELECT_ALL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.VALUE",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasMethods.setSelectionPosition",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasMethods.setSelectionPosition);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.INPUT_EVENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.INPUT_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.VALUE_CHANGE_EVENT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.VALUE_CHANGE_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.TextAreaFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.FIELDNAME",
				org.appops.ui.gwt.fieldex.TextFieldEx.FIELDNAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.MAX_LENGTH",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.MAX_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VISIBLE_LENGTH",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VISIBLE_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTED_TEXT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTED_TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_START",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_START);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_END",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_END);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECT_ALL",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECT_ALL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VALUE",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.INPUT_EVENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.INPUT_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.VALUE_CHANGE_EVENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.VALUE_CHANGE_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasMethods.setSelectionPosition",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasMethods.setSelectionPosition);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.CENTER",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.CENTER);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.JUSTIFY",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.JUSTIFY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.LEFT",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.LEFT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.RIGHT",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.RIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.MAX_LENGTH",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.MAX_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VISIBLE_LENGTH",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VISIBLE_LENGTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTED_TEXT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTED_TEXT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.READ_ONLY",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.READ_ONLY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT_ALIGNMENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TEXT_ALIGNMENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_START",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_START);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_END",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECTION_END);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.WIDTH",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.WIDTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.HEIGHT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.HEIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECT_ALL",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.SELECT_ALL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VALUE",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.VALUE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TITLE",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasProperties.TITLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.INPUT_EVENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.INPUT_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.CLICK_EVENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.CLICK_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.VALUE_CHANGE_EVENT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.VALUE_CHANGE_EVENT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_OUT",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_OUT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_IN",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_IN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_UP",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_UP);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_DOWN",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasEvents.MOUSE_KEY_DOWN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.HasMethods.setSelectionPosition",
				org.appops.ui.gwt.fieldex.TextFieldEx.HasMethods.setSelectionPosition);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.CENTER",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.CENTER);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.JUSTIFY",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.JUSTIFY);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.LEFT",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.LEFT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.RIGHT",
				org.appops.ui.gwt.fieldex.TextFieldEx.TextAlignment.RIGHT);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.PRIMARY_STYLE_NAME",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.PRIMARY_STYLE_NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.NAME",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.VISIBLE",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.VISIBLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ENABLE",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ENABLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ACTIVE",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ACTIVE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.PRIMARY_STYLE_NAME",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.PRIMARY_STYLE_NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.NAME",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.NAME);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.VISIBLE",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.VISIBLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ENABLE",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ENABLE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ACTIVE",
				org.appops.ui.gwt.fieldex.core.BaseFieldEx.HasProperties.ACTIVE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.VariableEx.VOID",
				org.appops.ui.gwt.fieldex.core.VariableEx.VOID);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.core.VariableEx.NULL",
				org.appops.ui.gwt.fieldex.core.VariableEx.NULL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.eventex.ValueChangeEventEx.VALUE_CHANGED",
				org.appops.ui.gwt.fieldex.eventex.ValueChangeEventEx.VALUE_CHANGED);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.exprex.Operator.AND",
				org.appops.ui.gwt.fieldex.exprex.Operator.AND);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.exprex.Operator.OR",
				org.appops.ui.gwt.fieldex.exprex.Operator.OR);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.exprex.Operator.ADD",
				org.appops.ui.gwt.fieldex.exprex.Operator.ADD);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.exprex.Parentheses.OPEN",
				org.appops.ui.gwt.fieldex.exprex.Parentheses.OPEN);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.exprex.Parentheses.CLOSE",
				org.appops.ui.gwt.fieldex.exprex.Parentheses.CLOSE);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.FIRST",
				org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.FIRST);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.VisibleDeck",
				org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.VisibleDeck);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.InvisibleDeck",
				org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.InvisibleDeck);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.VisibleDeck",
				org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.VisibleDeck);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.InvisibleDeck",
				org.appops.ui.gwt.fieldex.layoutex.DeckElementEx.DeckStyleConstant.InvisibleDeck);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.NORTH",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.NORTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.SOUTH",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.SOUTH);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.EAST",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.EAST);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.WEST",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.WEST);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.CENTER",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.BorderRegion.CENTER);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.Direction.VERTICAL",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.Direction.VERTICAL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.Direction.HORIZONTAL",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.Direction.HORIZONTAL);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.FlowRegion.FIRST",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.FlowRegion.FIRST);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.FlowRegion.LAST",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.FlowRegion.LAST);
		staticReferencesMap.put("org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.FlowRegion.AFTER",
				org.appops.ui.gwt.fieldex.layoutex.LayoutConstants.FlowRegion.AFTER);

	}
}
